### ISSUE TITLE
representation learning을 어떻게 번역하면 좋을까요? ^^

### ISSUE THREAD

**Issue by rickiepark** [keunwoochoi/machine_learning_eng2kor#1]
안녕하세요. 
representation learning을 어떻게 옮겨야 할 지 난감하네요. 구글로는 표현 학습, 표상 학습 정도가 찾아지는 데 왠지 직관적이지 않은 것 같아서요. 혹시 좋은 생각 있으시면 알려 주세요. :)
감사합니다.

**Comment by keunwoochoi** [comment]
아.. 어렵네요. 저는 표상보다는 표현이 맘에 듭니다. 어느 정도의 어색함은 어쩔 수 없는것 같아요.

**Comment by rickiepark** [comment]
네 저도 표현이 조금 나은 것 같습니다. 어느 정도의 어색함은 감수해야 겠네요. 감사합니다. ^^

**Comment by Choiuijin1125** [comment]
저도 representation에 대한 번역이 난감해서 이래저래 찾아보고 있었는데, 여기서 만나네요 ! :) @rickiepark

**Comment by rickiepark** [comment]
@Choiuijin1125 👍
